title: Tiến Thành's Home
# Include external resources
resources:
  - url: /local/my-custom-card.js
    type: js
  - url: /local/my-webfont.css
    type: css
  - url: /local/custom_ui/weather-card.js?v=1
    type: js
  - url: /local/custom_ui/dark-sky-weather-card.js?v=5
    type: js
  - url: /local/custom_ui/card-modder.js
    type: module
  - url: /local/mini-media-player-bundle.js?v=0.9.2 # https://community.home-assistant.io/t/lovelace-mini-media-player/68459
    type: module



# Optional background for all views. Check https://developer.mozilla.org/en-US/docs/Web/CSS/background for more examples.
background: center / cover no-repeat url("/background.png") fixed
# Exclude entities from "Unused entities" view
excluded_entities:
  - weblink.router

views:
  - title: Tổng quan
    icon: mdi:home-assistant
    cards:
      - type: entity-filter
        entities:          
          - entity: switch.balcony_light
            tap_action: toggle    
          - entity: switch.bedroom_light
            tap_action: toggle      
          - entity: switch.toilet_2
            tap_action: toggle
          - entity: switch.fan_kangaroo
            tap_action: toggle
          - entity: switch.heater_3
            tap_action: toggle
            


        #  - entity: input_select.temp1
        state_filter:
          - "on"
        show_empty: false
        card: 
          type: glance
          title: Thiết bị đang bật
          column_width: calc(100% / 3)



      - type: entities
        title: Điều khiển
        show_header_toggle: false
        #show_name: True
        #show_state: false
        #column_width: calc(100% / 3)
        entities:
          - entity: switch.bedroom_light
            tap_action: toggle
          - entity: switch.fan_kangaroo
            name: Siêu quạt
            tap_action: toggle
          - entity: switch.balcony_light
            tap_action: toggle
          - entity: switch.heater_3
            tap_action: toggle
          - entity: switch.toilet_2
            tap_action: toggle
          - entity: input_select.temp1
          
          
          - type: divider
            style: 
              height: 2px
              background-color: "#48f442"
          - type: weblink
            name: Thành Đỗ Tiến
            icon: mdi:link
            url: https://www.facebook.com/thanhdotien278  

      - type: entities
        title: Tự động hoá
        show_header_toggle: false
        #show_name: True
        #show_state: false
        #column_width: calc(100% / 3)
        entities:
          - entity: switch.motion_detection_amcrest_camera
            tap_action: toggle
          - entity: switch.motion_recording_amcrest_camera
            tap_action: toggle
      
          - type: call-service
            name: Bình nóng lạnh
            icon: mdi:hot-tub
            action_name: Bật 15'
            service: script.batnonglanh3
            service_data:
              entity_id: script.batnonglanh3



      - type: entities
        title: Trong phòng
        show_header_toggle: false
        entities:
          - entity: sensor._temperature
          - entity: sensor._humidity
          - entity: sensor.tiengon
          - entity: sensor.cuongdoanhsang
          - entity: sensor.chatluongkhongkhi

      

    
        

          
          
          
      - type: entities
        title: Ngoài trời
        show_header_toggle: false
        entities:
          - entity: sensor.weathertoday
          - entity: sensor.dark_sky_temperature 
          - entity: sensor.dark_sky_uv_index
          - entity: sensor.dark_sky_pressure
          - entity: sensor.dark_sky_humidity
          - entity:  sensor.dark_sky_wind_speed
          - entity: sensor.dark_sky_daytime_high_temperature          
          - entity: sensor.dark_sky_overnight_low_temperature

#################################################################
#                                                               #
#                         Date & Time                           #
#                                                               #
################################################################# 
      - id: cb489d24f3c64db1a6a96cdc70a4cc26  # Automatically created id
        type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: custom:card-modder
                card:
                  type: picture-entity
                  entity: sensor.date
                  image: https://images.pexels.com/photos/9352/glass-time-watch-business.jpg?cs=srgb&dl=clock-hours-minutes-9352.jpg&fm=jpg
                  tap_action: more-info
                style:                 
                  border-radius: 20px
                  border: solid 1px rgba(100,100,100,0.3)
                  box-shadow: 3px 3px rgba(0,0,0,0.4)  
                  
              - type: custom:card-modder
                card:
                  type: picture-entity
                  entity: sensor.time
                  image: https://images.pexels.com/photos/9352/glass-time-watch-business.jpg?cs=srgb&dl=clock-hours-minutes-9352.jpg&fm=jpg
                  tap_action: more-info
                style:                 
                  border-radius: 20px
                  border: solid 1px rgba(100,100,100,0.3)
                  box-shadow: 3px 3px rgba(0,0,0,0.4)  
#eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE4NTYxNzEzODMsImlzcyI6IjgyYzg0MmFhNjgyZTQ2MzZhMmNmYjM2OWM1ODgyY2E5IiwiaWF0IjoxNTQwODExMzgzfQ.pxD8rBTIpS4IeXosFnSjmWkNXB5UA1WJ8MJPwJtgSAs





        # The markdown card will render markdown text.
      - type: markdown
        title: Phòng ngủ
        content: >
          'Welcome to your Love Room'

# ######## Weather Tab ##################


  - title: Thời tiết
    icon: mdi:weather-lightning-rainy
    # Optional unique id for direct access /lovelace/${id}
    id: weather_tab
    # Optional background (overwrites the global background).
    background: radial-gradient(crimson, skyblue)
    # Each view can have a different theme applied. Theme should be defined in the frontend.
    theme: dark-mode
    # The cards to show on this view.
    cards:

      - type: custom:weather-card
        entity_weather: weather.yweather
        entity_sun: sun.sun

      - type: custom:dark-sky-weather-card
        entity_sun: sun.sun
        entity_daily_summary: sensor.dark_sky_daily_summary
        entity_current_conditions: sensor.dark_sky_icon
        entity_humidity: sensor.dark_sky_humidity #sensor.dark_sky_humidity
        entity_pressure: sensor.dark_sky_pressure
        entity_temperature: sensor.dark_sky_temperature #sensor.dark_sky_temperature
        entity_visibility: sensor.dark_sky_visibility
        entity_wind_bearing: sensor.dark_sky_wind_bearing
        entity_wind_speed: sensor.dark_sky_wind_speed
        entity_forecast_high_temp_1: sensor.dark_sky_daytime_high_temperature_1
        entity_forecast_high_temp_2: sensor.dark_sky_daytime_high_temperature_2
        entity_forecast_high_temp_3: sensor.dark_sky_daytime_high_temperature_3
        entity_forecast_high_temp_4: sensor.dark_sky_daytime_high_temperature_4
        entity_forecast_high_temp_5: sensor.dark_sky_daytime_high_temperature_5
        entity_forecast_low_temp_1: sensor.dark_sky_overnight_low_temperature
        entity_forecast_low_temp_2: sensor.dark_sky_overnight_low_temperature_1
        entity_forecast_low_temp_3: sensor.dark_sky_overnight_low_temperature_2
        entity_forecast_low_temp_4: sensor.dark_sky_overnight_low_temperature_3
        entity_forecast_low_temp_5: sensor.dark_sky_overnight_low_temperature_4
        entity_forecast_icon_1: sensor.dark_sky_icon_1
        entity_forecast_icon_2: sensor.dark_sky_icon_2
        entity_forecast_icon_3: sensor.dark_sky_icon_3
        entity_forecast_icon_4: sensor.dark_sky_icon_4
        entity_forecast_icon_5: sensor.dark_sky_icon_5


      - type: weather-forecast
        entity: weather.yweather
        title: Dự báo thời tiết
        # The filter card will filter entities for their state
      - type: history-graph
        title: Nhiệt độ 24h qua
        entities:
          - entity: sensor.dark_sky_temperature
            name: Ngoài trời
          - entity: sensor._temperature
            name: Trong phòng
      - type: history-graph
        title: Độ ẩm 24h qua
        entities:      
          - entity: sensor.dark_sky_humidity
            name: Ngoài trời    
          - entity: sensor._humidity
            name: Trong phòng
  #################################################################
#                                                               #
#                        TAB SYSTEM                             #
#                                                               #
################################################################# 

  - title: Hệ thống  #Processor
    icon: mdi:chip
    # Optional unique id for direct access /lovelace/${id}
    id: example
    # Optional background (overwrites the global background).
    background: radial-gradient(crimson, skyblue)
    # Each view can have a different theme applied. Theme should be defined in the frontend.
    theme: dark-mode
    # The cards to show on this view.
    cards:
        # The filter card will filter entities for their state
      - type: entity-filter
        entities:
          - device_tracker.thanhdaika_thanhdaika
          - device_tracker.anne_there
        state_filter:
          - 'home'
        card:
          type: glance
          title: People that are home

      - type: entities
        name: Raspberry Pi
        entities:
          - entity: sensor.processor_use
          - entity: sensor.memory_use_percent
          - entity: sensor.disk_free_
          - entity: sensor.network_in_wlan0
          - entity: sensor.network_out_wlan0
          - entity: sensor.last_boot
          - entity: sensor.since_last_boot
          - entity: sensor.speedtest_download
          #- entity: device_tracker.thanhdaika_thanhdaika
          - entity: sensor.battery_myphone
          - entity: sensor.battery_tablet
          - entity: sensor.mattroi

          

  - title: Thu nghiem
    icon: mdi:accusoft
    cards:
      - type: picture-entity
        entity: switch.bedroom_light
        tap_action: toggle
        state_image:
          "on": /local/light_on.jpg
          "off": /local/light_off.jpg
      - type: glance
        title: Scripts
        entities:
          - entity: script.battatden
            name: Bật tắt đèn 
            tap_action: toggle
      - type: picture-glance
        entities:
          - switch.bedroom_light
          - switch.balcony_light
          - switch.fan_kangaroo
        state_image:
          "on": /local/light_on.jpg
          "off": /local/light_off.jpg
        entity: switch.balcony_light
      - type: glance
        title: Phòng ngủ của nhà Mỳ Tôm
        show_name: True
        show_state: false
        column_width: calc(100% / 3)
        entities:
          - entity: switch.bedroom_light
            name: Đèn phòng ngủ
            tap_action: toggle
          - entity: switch.fan_kangaroo
            name: Siêu quạt
            tap_action: toggle
          - entity: switch.balcony_light
            # Override the name to use
            name: Đèn ban công
            tap_action: toggle

#################################################################
#                                                               #
#                        Multimedia                            #
#                                                               #
################################################################# 
  - icon: mdi:arrow-right-drop-circle
    id: Multimedia_tab
    title: Multimedia
    cards:
      - type: media-control
        title: Entertainment
        show_header_toggle: false
        entity: media_player.google_home
      - type: picture-entity
        entity: camera.yosee_camra
      - type: picture-entity
        entity: camera.amcrest_camera
      
      - type: entities
        title: Media Players
        entities:
           - entity: media_player.google_home
             type: custom:mini-media-player
          #   hide_controls: true
             show_tts: google
             group: true
           - entity: media_player.home_mini
             name: Loa Phòng làm việc
             type: custom:mini-media-player
             hide_controls: false
             group: true
             show_progress: true
            # hide_power: true
             show_source: true
             #artwork: cover
             artwork_border: true
             show_tts: google

      

        


        
          

  
  

     
