- alias: "Power state of Dining room light on HA start-up"
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: "cmnd/dining/power1"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "cmnd/dining/power2"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "cmnd/dining/power3"
        payload: ""


- alias: "Power state of Bedroom light on HA start-up"
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: "cmnd/bedroom3/power1"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "cmnd/bedroom3/power2"
        payload: ""

- alias: "Power state of Toilet light 2 on HA start-up"
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: "cmnd/toilet2/power"
        payload: ""

- alias: "Power state of Heater 3 on HA start-up"
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: "cmnd/heater3/power"
        payload: ""