homeassistant:
  #title: Home
  # Name of the location where Home Assistant is running
  name: Tiến Thành's Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  # C for Celcius, F for Fahrenheit
  temperature_unit: C
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Ho_Chi_Minh
  # Customization file
  
  whitelist_external_dirs:
    - /tmp

panel_iframe:
  mdiindex:
    title: MDI Icons Index
    icon: mdi:vector-square
    url: https://cdn.rawgit.com/james-fry/home-assistant-mdi/efd95d7a/home-assistant-mdi.html
   # - '/home/homeassistant/.homeassistant/downloads/camera/'
   # - '/home/homeassistant/.homeassistant/downloads/camera/porch'
   # - '/home/homeassistant/.homeassistant/downloads/camera/patio'
   # - '/home/homeassistant/.homeassistant/downloads/camera/backyard'
   # - '/home/homeassistant/.homeassistant/downloads/camera/driveway'
# Show links to resources in log and frontend
#introduction:



# Enables the frontend
frontend:

# Enables configuration UI
config:

weather:
  - platform: yweather
    woeid:  91925412

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret base_url
  server_port: !secret server_port
  api_password: !secret api_passwd
  login_attempts_threshold: 3

google_assistant:
  project_id: !secret google_project_id
  api_key: !secret google_project_api_key
  exposed_domains:
    - switch
    - light

updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:



# Enables support for tracking state changes over time
history:

zone:
  - name: Work
    latitude: !secret latitude_work
    longitude: !secret longitude_work
    radius: 250
    icon: mdi:school

  - name: Wife's Company
    latitude: !secret latitude_work_w
    longitude: !secret longitude_work_w
    icon: mdi:bank

  # This will override the default home zone
  - name: Home
    latitude: 20.971193
    longitude: 105.784816
    radius: 100
    icon: mdi:account-multiple


# View all events in a logbook
logbook:


mqtt:
  broker: superman153.duckdns.org
  #keepalive: 60
  port: 1883
  username: mosq
  password: !secret mosq_passwd
  protocol: 3.1.1



device_tracker:
  - platform: owntracks
    max_gps_accuracy: 200
    waypoints: true
    mqtt_topic: "owntracks/mosq/MIMI"
    events_only: true

# Enables a map showing the location of tracked devices
map:


amcrest:
  - host: !secret amcrest_ip
    username: !secret amcrest_user
    password: !secret amcrest_pass
    resolution: low
    sensors:
      - motion_detector
      - sdcard
    switches:
      - motion_detection
      - motion_recording

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

camera:
  - platform: ffmpeg
    input: rtsp://192.168.2.10/onvif1
    name: Yosee Camra
  - platform: amcrest













# Track the sun
sun:

# Weather prediction
#sensor:
#  - platform: yr

# Text to speech
tts:
  - platform: google
    cache_dir: /tmp/tts
    time_memory: 300
    language: 'vi'
    cache: true



ifttt:
  key: mB2F_GbB4jzOamgSLoJXTBR4SvFv3MqiWVdxIRc3zrl

ring:
  username: !secret ring_user
  password: !secret ring_pwd


customize: !include customize.yaml
switch: !include switches.yaml
cloud:
group: !include groups.yaml
automation: !include automations.yaml
input_select: !include input_select.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensor.yaml
script: !include scripts.yaml
recorder: !include recorder.yaml
